#!/usr/bin/env bash

function _get_instance_az () {
    INSTANCE_ID="$1"
    REGION="$2"
    PROFILE="$3"
    aws ec2 describe-instances --instance-ids="$INSTANCE_ID" --query 'Reservations[0].Instances[0].Placement.AvailabilityZone' --region "$REGION" --profile "$PROFILE" --output text
}

function _send_ssh_public_key_to_instance () {
    INSTANCE_ID="$1"
    USER_NAME="$2"
    KEY_FILE="$3"
    AZ="$4"
    REGION="$5"
    PROFILE="$6"
    aws ec2-instance-connect send-ssh-public-key --instance-id "$INSTANCE_ID" --availability-zone "$AZ" --instance-os-user "$USER_NAME" --ssh-public-key "file://$KEY_FILE" --region "$REGION" --profile "$PROFILE"
}

function _usage {
    cat <<EOF
$(basename ${0}): ssh to ec2 instance via ssm/instance-connect

Requirements:
    - AWS CLI is installed.
    - Permission to run "aws ssm start-session".
    - Permission to run "aws ec2 describe-instances" to determine which AZ the instance is in.
    - Permission to run "aws ec2-instance-connect send-ssh-public-key"
    - SSH connections through the SessionManager are allowed in ~/.ssh/config as shown below.
      (see: https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-getting-started-enable-ssh-connections.html)
        host i-* mi-*
            ProxyCommand sh -c "ssh_ec2 %h --port-number %p --profile xxx"

Usage:
    $(basename ${0}) <instance-id> [--key-file <key-file>] [--user <user>] [--port-number <port-number>] [--region <region>] [--profile <profile>] [--send-key-only]

Options:
    instance-id:        ID of the instance to ssh to.(e.g. "i-12345678")
    user-name:          User name to ssh as.(e.g. "ec2-user")
    --key-file:         (default: "\$HOME/.ssh/id_rsa.pub")
    --send-key-only:    Only transfer the key and do not execute ssh command. (default: false)
    --user:             (default: "ubuntu")
    --port-number:      (default: 22)
    --region:           (default: "ap-northeast-1")
    --profile:          (default: "default")
EOF
}

INSTANCE_ID="$1"
if [[ -z "${INSTANCE_ID}" ]]; then
    _usage 1>&2
    exit 1
fi
shift

while test ${#} -gt 0
do
    case $1 in
        --key-file)
            KEY_FILE=$2
            shift
            ;;
        --send-key-only)
            SEND_KEY_ONLY=true
            ;;
        --user)
            USER_NAME=$2
            shift
            ;;
        --port-number)
            PORT_NUMBER=$2
            shift
            ;;
        --region)
            REGION=$2
            shift
            ;;
        --profile)
            PROFILE=$2
            shift
            ;;
    esac
    shift
done

if [[ -z "${KEY_FILE}" ]]; then
    KEY_FILE="$HOME/.ssh/id_rsa.pub"
fi

if [[ -z "${USER_NAME}" ]]; then
    USER_NAME="ubuntu"
fi

if [[ -z "${REGION}" ]]; then
    REGION="ap-northeast-1"
fi

if [[ -z "${PROFILE}" ]]; then
    PROFILE="default"
fi

AZ=`_get_instance_az "$INSTANCE_ID" "$REGION" "$PROFILE"`

_send_ssh_public_key_to_instance "$INSTANCE_ID" "$USER_NAME" "$KEY_FILE" "$AZ" "$REGION" "$PROFILE"

if [[ -z "${SEND_KEY_ONLY}" ]]; then
    aws ssm start-session --target "$INSTANCE_ID" --document-name AWS-StartSSHSession --parameters portNumber=${PORT_NUMBER} --profile ${PROFILE} --region ${REGION}
fi

